
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action CODEAction;
	
	private global::Gtk.Action openAction;
	
	private global::Gtk.Action CLEARAction;
	
	private global::Gtk.Action saveAction;
	
	private global::Gtk.Action clearAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	
	private global::Gtk.TextView codearea;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView lexemearea;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TreeView symbolarea;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView consolearea;
	
	private global::Gtk.HButtonBox hbuttonbox2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.CODEAction = new global::Gtk.Action ("CODEAction", global::Mono.Unix.Catalog.GetString ("CODE"), null, null);
		this.CODEAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("CODE");
		w1.Add (this.CODEAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open File"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open File");
		w1.Add (this.openAction, null);
		this.CLEARAction = new global::Gtk.Action ("CLEARAction", global::Mono.Unix.Catalog.GetString ("CLEAR"), null, null);
		this.CLEARAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("CLEAR");
		w1.Add (this.CLEARAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save File"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save File");
		w1.Add (this.saveAction, null);
		this.clearAction = new global::Gtk.Action ("clearAction", global::Mono.Unix.Catalog.GetString ("Clear"), null, "gtk-clear");
		this.clearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clear");
		w1.Add (this.clearAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='CODEAction' action='CODEAction'><menuitem name='openAction' action='openAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow3.BorderWidth = ((uint)(5));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.codearea = new global::Gtk.TextView ();
		this.codearea.CanFocus = true;
		this.codearea.Name = "codearea";
		this.GtkScrolledWindow3.Add (this.codearea);
		this.hbox1.Add (this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow3]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("LEXEMES");
		this.label4.WidthChars = 30;
		this.vbox3.Add (this.label4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label4]));
		w5.Position = 0;
		w5.Expand = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow1.BorderWidth = ((uint)(5));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.lexemearea = new global::Gtk.TreeView ();
		this.lexemearea.CanFocus = true;
		this.lexemearea.Name = "lexemearea";
		this.GtkScrolledWindow1.Add (this.lexemearea);
		this.vbox3.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow1]));
		w7.Position = 1;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("SYMBOL TABLE");
		this.label5.WidthChars = 30;
		this.vbox6.Add (this.label5);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label5]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow2.BorderWidth = ((uint)(5));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.symbolarea = new global::Gtk.TreeView ();
		this.symbolarea.CanFocus = true;
		this.symbolarea.Name = "symbolarea";
		this.GtkScrolledWindow2.Add (this.symbolarea);
		this.vbox6.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow2]));
		w11.Position = 1;
		this.hbox1.Add (this.vbox6);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox6]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w13.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.BorderWidth = ((uint)(2));
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("EXECUTE");
		this.hbox3.Add (this.button1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button1]));
		w14.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.BorderWidth = ((uint)(2));
		global::Gtk.Image w15 = new global::Gtk.Image ();
		w15.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_trash_full", global::Gtk.IconSize.Menu);
		this.button2.Image = w15;
		this.hbox3.Add (this.button2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button2]));
		w16.PackType = ((global::Gtk.PackType)(1));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		w16.Padding = ((uint)(2));
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w18.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(4));
		this.GtkScrolledWindow.BorderWidth = ((uint)(5));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.consolearea = new global::Gtk.TextView ();
		this.consolearea.CanFocus = true;
		this.consolearea.Name = "consolearea";
		this.consolearea.Editable = false;
		this.consolearea.CursorVisible = false;
		this.GtkScrolledWindow.Add (this.consolearea);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
		w20.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		this.vbox4.Add (this.hbuttonbox2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbuttonbox2]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.CanFocus = true;
		this.label2.Events = ((global::Gdk.EventMask)(262144));
		this.label2.Name = "label2";
		this.label2.Yalign = 1F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("CMSC 124 B-3L GRP ABC");
		this.label2.Wrap = true;
		this.label2.Justify = ((global::Gtk.Justification)(2));
		this.label2.Ellipsize = ((global::Pango.EllipsizeMode)(1));
		this.hbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
		w22.Position = 0;
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
		w24.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 882;
		this.DefaultHeight = 597;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.openFile);
		this.button1.Clicked += new global::System.EventHandler (this.execute);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
